### ISSUE TITLE
Major rev release

### ISSUE THREAD

**Issue by rvonkeys** [nginxinc/new-relic-agent#6]
Shouldn't the current release version be 3.0.0 instead of 2.0.1.  It introduces a breaking change with the removal of legacy status support.

**Comment by Dean-Coakley** [comment]
Hi @rvonkeys 

Very sorry there has been such a delay in responding to your issue.

Sounds reasonable. I'm looking into what can be done next. I'll update you with any findings.

**Comment by Dean-Coakley** [comment]
You're correct that 2.0.0->2.0.1 does introduce a breaking change, and 2.0.1 should have been released as 3.0.0.

However we have decided to not retroactively update the current release to be 3.0.0. As this would suggest breaking changes between 2.0.1 and 3.0.0

Thanks for reporting this.
