### ISSUE TITLE
Would it be possible to tag the latest and the future releases?

### ISSUE THREAD

**Issue by sudarkoff** [nginxinc/new-relic-agent#7]
Our internal build pipeline is pinned and pulling a particular release of the package from this repository. SHA1 works, but having a symbolic tag would be a lot more descriptive. Thanks!

**Comment by Dean-Coakley** [comment]
Hi @sudarkoff 

Apologies for the delay in my response.

Just want to clarify: you want current/future releases to be marked with `git tag` so you can pull a specific release more easily?

**Comment by alex-mesfin** [comment]
I second @sudarkoff request for a tagged and or pinned version.

**Comment by Dean-Coakley** [comment]
@sudarkoff @alex-mesfin Git tag `v2.0.1` is now available.

Thanks for the request!
